### ISSUE TITLE
EPIC: Identifying Expected Network Traffic Rate in celestia-core

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/celestia-core#1080]
## Problem and Context
We have conducted a series of tests aimed at assessing the network's performance and overall health using various infrastructures. These tests have been performed in live networks like Mocha, as well as in test environments such as Testground and Knuu. Throughout these evaluations, we have monitored multiple performance indicators, including transaction throughput, block size, and block time. Additionally, we have also considered various health indicators, such as traffic rates per peer.

A recurring theme in all these scenarios is the need to answer critical questions: What are the expected outcomes? What constitutes healthy behavior? Depending on the answers to these questions, our test results become significantly more insightful, allowing us to pinpoint bottlenecks and disparities effectively.

In this EPIC, we provide a plan to address these questions for the **network traffic rate**.

## Solution Plan
Setting a baseline for the expected traffic rate in a healthy network necessitates an understanding of the inner workings of the P2P layer within Celestia-Core (Tendermint) potentially by utilizing some low-level specification (which unfortunately is not available). However, our preliminary analysis has revealed that we are currently dealing with a limited number of reactors (channel IDs) and message types at the p2p layer. Thus, we can simplify this process by only focusing on extracting and documenting the flow of messages through their reactors and in relation to the number of connections and the state of the consensus. This would allow us to set an expected traffic rate per peer depending on the test scenario and network topology (and other factors that may come up as part of this EPIC)

Our approach involves an examination of the code associated with each message type, with a focus on understanding their life cycles. This entails:
- When and under what conditions they are generated (e.g., height-based, round-based, or other criteria).
- How they are propagated (e.g., in relation to connected peers, whether on request or through push mechanisms, or other contributing factors).
- Determining the message size and factors contributing to its variability (e.g., block size).

## Tasks
The following list categorizes message types based on their channel IDs (note that the message names are according to how they appear on the Prometheus metrics endpoint and may differ from their protobuf names). In this EPIC, we need to address questions outlined in the Solution Plan section for each of these message types and document the findings. Prioritization should be given to documenting message types that have contributed the most to overall traffic, as indicated by the results obtained in the previous [issue](https://github.com/celestiaorg/celestia-app/issues/2197). For reference, please find the screenshot of the results below:

![Screenshot 2023-09-14 at 10:53:30 AM](https://github.com/celestiaorg/celestia-core/assets/35961250/99a5726f-6b7f-4c48-b04a-a69440943163)

- 0x30 
  - [x] mempool_Txs -> #1108 
- 0x21 
  - [ ] consensus_BlockPart -> https://github.com/celestiaorg/celestia-core/pull/1129
  - [ ] consensus_Proposal -> https://github.com/celestiaorg/celestia-core/pull/1129
- 0x0 
  - [ ] p2p_PexAddrs 
  - [ ] p2p_PexRequest
- 0x20 
  - [ ] consensus_HasVote 
  - [ ] consensus_NewRoundStep -> partially covered in https://github.com/celestiaorg/celestia-core/pull/1129
  - [ ] consensus_NewValidBlock 
  - [ ] consensus_VoteSetMaj23
- 0x22 
  - [ ] consensus_Vote
- 0x23
  - [ ] consensus_VoteSetBits
- 0x40 
  - [ ] blockchain_BlockRequest 
  - [ ] blockchain_BlockResponse 
  - [ ] blockchain_StatusRequest 
  - [ ] blockchain_StatusResponse

**Comment by staheri14** [comment]
Please consult the following table for mapping between channel ID and their names:</p>


Channel ID | Channel Description
-- | --
byte(0x40) | BlockchainChannel
byte(0x30) | MempoolChannel
byte(0x23) | VoteSetBitsChannel
byte(0x22) | VoteChannel
byte(0x21) | DataChannel
byte(0x20) | StateChannel
byte(0x00) | PexChannel

**Comment by cmwaters** [comment]
Nice work. This definitely helps to validate the impact to bandwidth that compact blocks would have (given the current significant bandwidth to block parts)
