### ISSUE TITLE
EPIC: Full Mesh

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#1479]
In order to decrease the number of hops required to distribute votes and block data, an full mesh network can be overlay where validators only communicate with each other. There is a strict requirement that this is not a simple replacement of the p2p stack. We only want to send specific data over this network.

- [ ] Add the ability to only send data directly instead of always gossiping it
- [ ] Add the ability to maintain a list of peers that are validators
- [ ] Add the ability for validators to authenticate themselves over the p2p stack
- [ ] Add the ability to gossip only other validator ips
