### ISSUE TITLE
EPIC: Vacuum!

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#1484]
The [in-progress] spec of vacuum! is located [here](https://hackmd.io/@cIFNimXuR8eiNlZuI5vvpw/HyFo5Jqh0).

- [ ] Add VACs and VACRoots
- [ ] Implement the VACPool
- [ ] Implement the VACReactor
- [ ] Reap prioritized and attested txs from the VACPool when creating a block

## Optional 
- [ ] Add BlobTx chunking
- [ ] https://github.com/celestiaorg/celestia-core/issues/1479
